import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { dark } from '@clerk/themes';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from './(auth)/_components/theme-provider';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <ClerkProvider appearance={{ baseTheme: dark}}>
=======
    // update clerk provider tags
    <ClerkProvider>
>>>>>>> f1bccfde9e6887b4a63512839b46edbf41d1ccbd
      <html lang='en'>
        <body className={inter.className}>
          <ThemeProvider
            attribute = "class"
            forcedTheme='dark'
            storageKey='home-stream-theme'
          > 
          {children}
          </ThemeProvider>
          </body>
      </html>
    </ClerkProvider>
  )

}
